name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20.18.0'
  NPM_VERSION: '10'

jobs:
  # Node backend build and test
  node:
    name: Build & Test Node Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: node/package-lock.json

      - name: Install node dependencies
        working-directory: ./node
        run: npm install

      - name: Build node
        working-directory: ./node
        run: npm run build --if-present

      - name: Run node tests
        working-directory: ./node
        run: npm test --if-present -- --passWithNoTests || true

      - name: Lint node code
        working-directory: ./node
        run: npm run lint --if-present

  # Frontend build and test
  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test --if-present -- --passWithNoTests || true

      - name: Lint frontend code
        working-directory: ./frontend
        run: npm run lint --if-present

  # Integration tests
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [node, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install all dependencies
        run: |
          cd node && npm install
          cd ../frontend && npm install

      - name: Start node server
        working-directory: ./node
        run: |
          npm run build --if-present
          timeout 30s npm run dev &
          sleep 10

      - name: Test API endpoints
        run: |
          curl -f http://localhost:8888/health || exit 1
          curl -f http://localhost:8888/api/node || exit 1

      - name: Start frontend
        working-directory: ./frontend
        run: |
          npm run build
          timeout 30s npm run dev &
          sleep 10

      - name: Test frontend
        run: |
          curl -f http://localhost:3000 || exit 1

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd node && npm install
          cd ../frontend && npm install

      - name: Run security audit
        run: |
          cd node && npm audit --audit-level=moderate
          cd ../frontend && npm audit --audit-level=moderate

  # Code quality
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd node && npm install
          cd ../frontend && npm install

      - name: Check code formatting
        run: |
          cd node && npm run format:check --if-present || true
          cd ../frontend && npm run format:check --if-present || true

      - name: Check TypeScript
        run: |
          cd node && npm run type-check --if-present || true
          cd ../frontend && npm run type-check --if-present || true

  # Build and package
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [node, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd node && npm install
          cd ../frontend && npm install

      - name: Build all packages
        run: |
          cd node && npm run build
          cd ../frontend && npm run build:production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            node/dist/
            frontend/.next/
            frontend/out/ 